WIP: moving to Qt 5, OS X first
* 'QChar' is deprecated, in a few places
* tests/auto/qcl:
FAIL!  : tst_QCL::argumentPassing() Compared floats are not the same (fuzzy compare)
   Actual   (buf[0]): 0
   Expected (3.0f)  : 3
   Loc: [/Users/liangqi/dev/git/qtopencl/tests/auto/qcl/tst_qcl.cpp(321)]
* tests/benchmarks/blur:
In file included from /Users/liangqi/dev/git/qtopencl/tests/benchmarks/blur/pixmapfilterwidget.cpp:42:
/Users/liangqi/dev/git/qtopencl/tests/benchmarks/blur/pixmapfilterwidget.h:46:10: fatal error: 'QtGui/private/qpixmapfilter_p.h' file not found
         ^
In file included from .moc/moc_pixmapfilterwidget.cpp:9:
.moc/../../../../../../dev/git/qtopencl/tests/benchmarks/blur/pixmapfilterwidget.h:46:10: fatal error: 'QtGui/private/qpixmapfilter_p.h' file not found
         ^
1 error generated.
make: *** [.obj/moc_pixmapfilterwidget.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [.obj/pixmapfilterwidget.o] Error 1
In file included from /Users/liangqi/dev/git/qtopencl/tests/benchmarks/blur/tst_blur.cpp:56:
/Users/liangqi/dev/git/qtopencl/tests/benchmarks/blur/pixmapfilterwidget.h:46:10: fatal error: 'QtGui/private/qpixmapfilter_p.h' file not found
         ^
* demos/mandelbrot crash

Change-Id: I5ec46248b4819c170e46ff98fd3644572d06a5d1